---
# tasks file for roles/node

- name: set disable firewalld and setenforce 0
  shell: systemctl disable firewalld
  shell: systemctl stop firewalld
  shell: systemctl stop postfix
  shell: systemctl disable postfix
  shell: setenforce 0
  shell: getenforce
  tags:
      - node

- name: yum install tools
  shell: yum install -y net-tools
  tags:
      - node

- name: add hosts
  lineinfile:
      path: /etc/hosts
      line: "{{hosts_dns}}"
  tags:
      - node

- name: rpm install
  #shell: rpm -i {{item}}
  shell: 
  #with_items:
  tags:
      - node
